"""initial migration

Revision ID: 077a297d4e51
Revises: 
Create Date: 2025-02-15 15:03:17.228169

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077a297d4e51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('engaged', sa.Boolean(), nullable=False),
    sa.Column('last_contacted', sa.Date(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_company'), 'lead', ['company'], unique=False)
    op.create_index(op.f('ix_lead_created'), 'lead', ['created'], unique=False)
    op.create_index(op.f('ix_lead_email'), 'lead', ['email'], unique=True)
    op.create_index(op.f('ix_lead_engaged'), 'lead', ['engaged'], unique=False)
    op.create_index(op.f('ix_lead_full_name'), 'lead', ['full_name'], unique=False)
    op.create_index(op.f('ix_lead_last_contacted'), 'lead', ['last_contacted'], unique=False)
    op.create_index(op.f('ix_lead_stage'), 'lead', ['stage'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_lead_stage'), table_name='lead')
    op.drop_index(op.f('ix_lead_last_contacted'), table_name='lead')
    op.drop_index(op.f('ix_lead_full_name'), table_name='lead')
    op.drop_index(op.f('ix_lead_engaged'), table_name='lead')
    op.drop_index(op.f('ix_lead_email'), table_name='lead')
    op.drop_index(op.f('ix_lead_created'), table_name='lead')
    op.drop_index(op.f('ix_lead_company'), table_name='lead')
    op.drop_table('lead')
    # ### end Alembic commands ###
